const appname = "eMart";
const appversion = "Version 1.0.0";
const credits = "Developer";
const email = "Email";
const emailHint = "admin@admin.com";
const password = "Password";
const passwordHint = "*********";
const retypePassword = "Retype Password";
const name = "Name";
const nameHint = "Developer";
const forgetPass = "Forget Password";
const login = "Log in";
const signup = "Sign Up";
const createNewAccount = "or, create a new account";
const loginWith = "Log in With";
const privacyPolicy = "Privacy Policy";
const termAndCond = "Terms and Conditions";
const alreadyHaveAccount = "Already have an Account?";
const home = "Home",
    categories = "Categories",
    cart = "Cart",
    account = "Account";
const searchanything = "Search Anything...",
    todayDeal = "Today's Deal",
    flashsale = "Flash Sale",
    topSellers = "Top Sellers",
    brand = "Brand",
    topCategories = "Top Categories",
    womenDress = "Women Dress",
    girlsWatches = "Girls Watches",
    mobilePhone = "Mobile Phone",
    boysGlasses = "Boys Glasses",
    tShirts = "Tshirts",
    girlsDress = "Girls Dresses",
    featuredProduct = "Featured Products",
    featuredCategories = "Featured Categories";
const womenClothing = "Women Clothing",
    menClothingFashion = "Men Clothing & Fashion",
    compAccess = "Computer & Acessories",
    automobile = "Automobile",
    kidtoys = "Kids & Toys",
    sports = "Sports",
    jewelry = "Jewelry",
    cellphone = "Cellphone & Tab",
    furniture = "Furniture";
const video = "Video",
    reviews = "Reviews",
    sellerpolicy = "Seller Policy",
    returnpolicy = "Return Policy",
    supportpolicy = "Support Policy",
    productsyoumaylike = "Products you may also like ";
const logout = "Log Out";
const wishlist = "My Wishlist", orders = "My Orders", messages = "Messages";
